/**
 * Clypra Text Effect Code Output - Clypra Integration Engine Core
 * Auto-generated by Clypra Text Effect Studio on 2026-05-26
 * File: SolarisInk.ts
 *
 * ⚠️  PASTE ZONE — do not edit manually.
 *     Drop the raw studio export here. The registry in registry.ts handles all wiring.
 *     Known studio bug: remove or replace any reference to undefined `className` in drawFrame.
 */

import { TextEffectDefinition } from "../types/types";

// ─── Config Interface ─────────────────────────────────────────────────────────

export interface SolarisInkConfig {
  width: number;
  height: number;
  text: string;
  fontFamily?: string;
  fontWeight?: number;
  fontStyle?: "normal" | "italic";
  fontSize?: number;
  letterSpacing?: number;
  lineHeight?: number;
  fillType?: "solid" | "linear" | "radial" | "pattern" | "none";
  fillColor?: string;
  fillGradientAngle?: number;
  fillGradientStops?: Array<{ color: string; offset: number }>;
  strokeEnabled?: boolean;
  strokeColor?: string;
  strokeWidth?: number;
  strokePosition?: "outside" | "center" | "inside";
  strokeOpacity?: number;
  strokeLineJoin?: "round" | "miter" | "bevel";
  shadowEnabled?: boolean;
  shadowColor?: string;
  shadowBlur?: number;
  shadowOffsetX?: number;
  shadowOffsetY?: number;
  shadowOpacity?: number;
  shadowType?: "drop" | "inner";
  bevelEnabled?: boolean;
  bevelDepth?: number;
  bevelHighlight?: string;
  bevelShadow?: string;
  bevelDirection?: "bottom-right" | "bottom" | "right";
  panelEnabled?: boolean;
  panelColor?: string;
  panelOpacity?: number;
  panelRadius?: number;
  panelPaddingX?: number;
  panelPaddingY?: number;
  panelStrokeEnabled?: boolean;
  panelStrokeColor?: string;
  panelStrokeWidth?: number;
  textPosX?: "left" | "center" | "right";
  textPosY?: "top" | "middle" | "bottom";
  /** Glow layer array — populated by the registry from the definition's glows[] field. */
  glowLayers?: Array<{
    enabled: boolean;
    color: string;
    blur: number;
    opacity: number;
    type: "outer" | "inner";
    strength?: number;
    spread?: number;
  }>;
}

// ─── Engine Class ─────────────────────────────────────────────────────────────

export class SolarisInkEngine {
  private cfg: Required<SolarisInkConfig>;

  constructor(config: SolarisInkConfig) {
    // Merge provided configuration with static studio defaults
    const defaults: Required<SolarisInkConfig> = {
      width: 800,
      height: 200,
      text: "CLYPRA",
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontStyle: "normal",
      fontSize: 85,
      letterSpacing: 1,
      lineHeight: 1.2,
      fillType: "solid",
      fillColor: "#FFFFFF",
      fillGradientAngle: 90,
      fillGradientStops: [
        { color: "#FDFBF7", offset: 0 },
        { color: "#EAE5D9", offset: 100 },
      ],
      strokeEnabled: true,
      strokeColor: "#000000",
      strokeWidth: 9,
      strokePosition: "outside",
      strokeOpacity: 100,
      strokeLineJoin: "round",
      shadowEnabled: false,
      shadowColor: "#3D2B1F",
      shadowBlur: 14,
      shadowOffsetX: 6,
      shadowOffsetY: 6,
      shadowOpacity: 90,
      shadowType: "drop",
      bevelEnabled: false,
      bevelDepth: 5,
      bevelHighlight: "#FFFFFF",
      bevelShadow: "#000000",
      bevelDirection: "bottom-right",
      panelEnabled: false,
      panelColor: "#1E1E26",
      panelOpacity: 80,
      panelRadius: 12,
      panelPaddingX: 40,
      panelPaddingY: 20,
      panelStrokeEnabled: false,
      panelStrokeColor: "#2A2A38",
      panelStrokeWidth: 2,
      textPosX: "center",
      textPosY: "middle",
      glowLayers: [{ enabled: true, color: "#FFDD00", blur: 20, opacity: 100, type: "outer", strength: 4, spread: 10 }],
    };

    this.cfg = {
      ...defaults,
      ...config,
    };
  }

  // Satisfies standard Clypra text engine contract
  advanceSteps(_steps: number): void {
    // Static effect — no-op
  }

  drawFrame(ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D, _ghostFrames?: ImageData[]): void {
    const { width, height, text, fontFamily, fontWeight, fontStyle, fontSize, letterSpacing, lineHeight, fillType, fillColor, fillGradientAngle, fillGradientStops, strokeEnabled, strokeColor, strokeWidth, strokePosition, strokeOpacity, strokeLineJoin, shadowEnabled, shadowColor, shadowBlur, shadowOffsetX, shadowOffsetY, shadowOpacity, shadowType, bevelEnabled, bevelDepth, bevelHighlight, bevelShadow, bevelDirection, panelEnabled, panelColor, panelOpacity, panelRadius, panelPaddingX, panelPaddingY, panelStrokeEnabled, panelStrokeColor, panelStrokeWidth, textPosX, textPosY } = this.cfg;

    // Clear — no background color bleed allowed
    ctx.clearRect(0, 0, width, height);
    ctx.imageSmoothingEnabled = true;

    // Font setup
    ctx.font = `${fontStyle} ${fontWeight} ${fontSize}px "${fontFamily}"`;
    ctx.lineJoin = strokeLineJoin;

    const lines = text.split("\n");
    const textBlockHeight = fontSize + (lines.length - 1) * fontSize * lineHeight;

    // Horizontal origin
    let startX = width / 2;
    let align: CanvasTextAlign = "center";
    if (textPosX === "left") {
      startX = panelEnabled ? panelPaddingX + 20 : 50;
      align = "left";
    } else if (textPosX === "right") {
      startX = width - (panelEnabled ? panelPaddingX + 20 : 50);
      align = "right";
    }
    ctx.textAlign = align;

    // Vertical origin
    let startY = (height - textBlockHeight) / 2 + fontSize * 0.8;
    if (textPosY === "top") {
      startY = (panelEnabled ? panelPaddingY + 20 : 40) + fontSize * 0.8;
    } else if (textPosY === "bottom") {
      startY = height - (panelEnabled ? panelPaddingY + 20 : 40) - textBlockHeight + fontSize * 0.8;
    }

    // Measure text bounds
    const lineWidths = lines.map((line) => {
      const prev = (ctx as any).letterSpacing;
      if (letterSpacing !== 0) (ctx as any).letterSpacing = `${letterSpacing}px`;
      const w = ctx.measureText(line).width;
      (ctx as any).letterSpacing = prev;
      return w;
    });
    const maxLineWidth = Math.max(...lineWidths, 10);

    let xMin = align === "center" ? startX - maxLineWidth / 2 : align === "right" ? startX - maxLineWidth : startX;
    const xMax = xMin + maxLineWidth;
    const yMin = startY - fontSize * 0.8;
    const yMax = yMin + textBlockHeight;

    // ── Helpers ──────────────────────────────────────────────────────────────

    const renderLines = (mode: "fill" | "stroke", style?: string | CanvasGradient, dx = 0, dy = 0) => {
      const prev = (ctx as any).letterSpacing;
      if (letterSpacing !== 0) (ctx as any).letterSpacing = `${letterSpacing}px`;
      if (style) mode === "fill" ? (ctx.fillStyle = style) : (ctx.strokeStyle = style);
      lines.forEach((line, i) => {
        const py = startY + i * fontSize * lineHeight;
        mode === "fill" ? ctx.fillText(line, startX + dx, py + dy) : ctx.strokeText(line, startX + dx, py + dy);
      });
      (ctx as any).letterSpacing = prev;
    };

    const renderWithShadowTrick = (mode: "fill" | "stroke", sColor: string, sBlur: number, sOffsetX: number, sOffsetY: number, opacity: number, overrideStyle = "#000", spread = 0) => {
      ctx.save();
      ctx.globalAlpha = opacity / 100;
      const shiftX = 10000;
      ctx.shadowColor = sColor;
      ctx.shadowBlur = sBlur;
      ctx.shadowOffsetX = shiftX + sOffsetX;
      ctx.shadowOffsetY = sOffsetY;

      const prev = (ctx as any).letterSpacing;
      if (letterSpacing !== 0) (ctx as any).letterSpacing = `${letterSpacing}px`;
      if (mode === "fill") ctx.fillStyle = overrideStyle;
      else ctx.strokeStyle = overrideStyle;

      const prevStroke = ctx.strokeStyle;
      const prevLW = ctx.lineWidth;
      if (spread > 0) {
        ctx.strokeStyle = overrideStyle;
        ctx.lineWidth = spread * 2;
        ctx.lineJoin = strokeLineJoin;
      }

      lines.forEach((line, i) => {
        const py = startY + i * fontSize * lineHeight;
        if (mode === "fill") {
          if (spread > 0) ctx.strokeText(line, startX - shiftX, py);
          ctx.fillText(line, startX - shiftX, py);
        } else {
          ctx.strokeText(line, startX - shiftX, py);
        }
      });

      (ctx as any).letterSpacing = prev;
      if (spread > 0) {
        ctx.strokeStyle = prevStroke;
        ctx.lineWidth = prevLW;
      }
      ctx.restore();
    };

    // ── 1. Background Panel ───────────────────────────────────────────────────
    if (panelEnabled) {
      ctx.save();
      ctx.globalAlpha = panelOpacity / 100;
      ctx.fillStyle = panelColor;
      const px = xMin - panelPaddingX;
      const py = yMin - panelPaddingY;
      const pw = xMax - xMin + 2 * panelPaddingX;
      const ph = textBlockHeight + 2 * panelPaddingY;
      ctx.beginPath();
      ctx.roundRect(px, py, pw, ph, panelRadius);
      ctx.fill();
      if (panelStrokeEnabled) {
        ctx.strokeStyle = panelStrokeColor;
        ctx.lineWidth = panelStrokeWidth;
        ctx.stroke();
      }
      ctx.restore();
    }

    // ── 2. Outer Glow Layers ──────────────────────────────────────────────────
    const glowLayers = this.cfg.glowLayers;
    glowLayers.forEach((layer) => {
      if (layer.enabled && layer.type === "outer" && layer.opacity > 0) {
        const n = Math.max(1, Math.min(20, layer.strength ?? 1));
        for (let i = 0; i < n; i++) {
          renderWithShadowTrick("fill", layer.color, layer.blur, 0, 0, layer.opacity, "#000", layer.spread ?? 0);
        }
      }
    });

    // ── 3. Drop Shadow ────────────────────────────────────────────────────────
    if (shadowEnabled && shadowType === "drop" && shadowOpacity > 0) {
      renderWithShadowTrick("fill", shadowColor, shadowBlur, shadowOffsetX, shadowOffsetY, shadowOpacity);
    }

    // ── 4. Bevel 3D Layers ────────────────────────────────────────────────────
    if (bevelEnabled && bevelDepth > 0) {
      ctx.save();
      for (let i = bevelDepth; i > 0; i--) {
        const dx = bevelDirection !== "bottom" ? i : 0;
        const dy = bevelDirection !== "right" ? i : 0;
        renderLines("fill", i === 1 ? bevelHighlight : bevelShadow, dx, dy);
      }
      ctx.restore();
    }

    // ── 5. Outside / Center Stroke ────────────────────────────────────────────
    if (strokeEnabled && strokeWidth > 0 && strokePosition !== "inside") {
      ctx.save();
      ctx.globalAlpha = strokeOpacity / 100;
      ctx.strokeStyle = strokeColor;
      ctx.lineWidth = strokePosition === "outside" ? strokeWidth * 2 : strokeWidth;
      renderLines("stroke");
      ctx.restore();
    }

    // ── 6. Base Fill ──────────────────────────────────────────────────────────
    ctx.save();
    let computedFill: string | CanvasGradient = fillColor;

    if (fillType === "linear" && fillGradientStops.length >= 2) {
      const rad = (fillGradientAngle * Math.PI) / 180;
      const cx = (xMin + xMax) / 2;
      const cy = (yMin + yMax) / 2;
      const r = Math.max(xMax - xMin, yMax - yMin) / 2;
      const grad = ctx.createLinearGradient(cx - Math.cos(rad) * r, cy - Math.sin(rad) * r, cx + Math.cos(rad) * r, cy + Math.sin(rad) * r);
      fillGradientStops.forEach((s) => grad.addColorStop(s.offset / 100, s.color));
      computedFill = grad;
    } else if (fillType === "radial" && fillGradientStops.length >= 2) {
      const cx = (xMin + xMax) / 2;
      const cy = (yMin + yMax) / 2;
      const r = Math.max(xMax - xMin, yMax - yMin) / 1.5;
      const grad = ctx.createRadialGradient(cx, cy, 2, cx, cy, r);
      fillGradientStops.forEach((s) => grad.addColorStop(s.offset / 100, s.color));
      computedFill = grad;
    }

    if (fillType !== "none") renderLines("fill", computedFill);
    ctx.restore();

    // ── 7. Inside Stroke (clip) ───────────────────────────────────────────────
    if (strokeEnabled && strokeWidth > 0 && strokePosition === "inside") {
      ctx.save();
      ctx.globalCompositeOperation = "source-atop";
      ctx.strokeStyle = strokeColor;
      ctx.lineWidth = strokeWidth * 2;
      ctx.globalAlpha = strokeOpacity / 100;
      renderLines("stroke");
      ctx.restore();
    }

    // ── 8. Inner Glow + Inner Shadow overlays ─────────────────────────────────
    glowLayers.forEach((layer) => {
      if (layer.enabled && layer.type === "inner" && layer.opacity > 0) {
        ctx.save();
        ctx.globalCompositeOperation = "source-atop";
        const n = Math.max(1, Math.min(20, layer.strength ?? 1));
        for (let i = 0; i < n; i++) {
          renderWithShadowTrick("fill", layer.color, layer.blur, 0, 0, layer.opacity, "transparent", layer.spread ?? 0);
        }
        ctx.restore();
      }
    });

    if (shadowEnabled && shadowType === "inner" && shadowOpacity > 0) {
      ctx.save();
      ctx.globalCompositeOperation = "source-atop";
      renderWithShadowTrick("fill", shadowColor, shadowBlur, shadowOffsetX, shadowOffsetY, shadowOpacity, "transparent");
      ctx.restore();
    }
  }
}

// ─── Definition ───────────────────────────────────────────────────────────────
// This is the metadata descriptor. Structural type — compatible with TextEffectDefinition.
export const SolarisInkDefinition: TextEffectDefinition = {
  id: "solaris-ink",
  name: "Solaris Ink",
  text: "CLYPRA",
  category: "metallic",
  description: "A custom Canvas 2D text effect named Solaris Ink with solid fill.",
  tags: ["studio-export", "custom-canvas", "solid"],
  font: {
    family: "Montserrat",
    weight: 700,
    style: "normal" as const,
    letterSpacing: 1,
    lineHeight: 1.2,
  },
  fills: [
    {
      type: "solid",
      color: "#FFFFFF",
      gradient: {
        angle: 90,
        stops: [
          { color: "#FDFBF7", offset: 0 },
          { color: "#EAE5D9", offset: 100 },
        ],
      },
    },
  ],
  strokes: [{ color: "#000000", width: 9, position: "outside", opacity: 100, lineJoin: "round" }],
  shadows: [],
  glows: [{ color: "#FFDD00", blur: 20, opacity: 100, type: "outer" }],
  panel: null,
};
